import {data} from './bimsum.json'
type bimtype = 'term' | 'word' | 'sentence' | 'paragraph' | 'story';

const terms = [
"A/C",
"condenser",
"acoustics",
"activity",
"ADA",
"addendum",
"agent",
"aggregate",
"agreement",
"allowance",
"alterations",
"alternate bid",
"application for payment",
"arcade",
"arch",
"architect",
"architects basic services",
"architect-engineer",
"architectural drawing",
"area wells",
"record drawings",
"astragal",
"atrium",
"back charge",
"backfill",
"backing",
"baffle",
"ballast",
"balloon framed wall",
"balustrade",
"barge",
"barge board",
"baseboard",
"bat",
"beam",
"bearing partition",
"bearing point",
"bearing wall",
"bearing header",
"bedrock",
"bid",
"bid bond",
"bid date",
"bid form",
"bid opening",
"bid price",
"bid tabulation",
"bid shopper",
"bidding documents",
"bidding period",
"bidding requirements",
"blue prints",
"blue stake",
"bonding company",
"breaker panel",
"breezeway",
"bridging",
"budget",
"building",
"building code",
"building envelope",
"building inspector",
"building permit",
"building process",
"built-up roof",
"butterfly roof",
"buttress",
"BTU",
"caisson",
"cantilever",
"cantilevered void",
"cavity wall",
"ceiling joist",
"CFM",
"change order",
"change order request",
"change order proposal",
"check valve",
"circuit",
"circuit breaker",
"Class A",
"Class C",
"closed bid",
"CO",
"codes",
"cold air return",
"collar beam",
"column",
"combustion air",
"compressor",
"concrete",
"condensate line",
"condensing unit",
"electrical conduit",
"construction documents",
"construct",
"construction",
"construction cost",
"construction documents",
"construction documents phase",
"construction document review",
"construction document review",
"construction management",
"construction management contract",
"construction phase",
"consultant",
"contract",
"contract administration",
"contract bond",
"contract documents",
"contract over-run",
"contract under-run",
"contract payment bond",
"contract performance bond",
"contract period",
"contract sum",
"contract time",
"contractual liability",
"contractor",
"contractor's option",
"contractor's qualification statement",
"contracting officer",
"control joint",
"cooling load",
"corbel",
"corner braces",
"cornice",
"cost codes",
"cost of work",
"cost plus fee agreement",
"cost-plus agreement",
"counter flashing",
"counterfort",
"crawl space",
"cricket",
"critical path",
"C.P.M.",
"cross bracing",
"cross bridging",
"cross tee",
"CSI",
"CSI master format",
"cull",
"cupola",
"cure",
"current date line",
"curtain wall",
"daily construction report",
"date of agreement",
"date of commencement of the work",
"date of substantial completion",
"dead load",
"demising walls",
"design",
"design-build",
"design-construct contract",
"design-development phase",
"detail",
"direct cost",
"direct expense",
"dormer",
"downspout",
"draw",
"drawings",
"drywall",
"duration",
"easement",
"eaves",
"egress",
"electrical rough",
"electrical trim",
"elevation",
"engineer",
"estimate",
"estimate of construction cost",
"estimating",
"excavation",
"expansion joint",
"fabrication",
"facade",
"facility",
"facility site analysis",
"fast track",
"FF&E",
"field order",
"field report",
"field work order",
"final acceptance",
"final inspection",
"final payment",
"finish date",
"fire resistive",
"fire rated",
"fire retardant",
"fire-stop",
"fixed fee",
"fixed limit",
"flashing",
"floating",
"floating-wall",
"form",
"footprint",
"foundation",
"foundation ties",
"gable",
"gambrel roof",
"gantt chart",
"general conditions",
"general contractor",
"girder",
"grade",
"grid",
"hard costs",
"heating load",
"heat rough",
"heat trim",
"hip",
"I-beram",
"independent contractor",
"improvements",
"indemnification",
"indirect cost",
"indirect expense",
"inspection",
"inspection for disbursement of funds",
"inspection list",
"punch list",
"inspection report ",
"inspector",
"interior finish",
"invoice",
"joist",
"labor and material",
"payment bond",
"leasehold improvements",
"mechanic's lien",
"material lien",
"lien release",
"lien waiver",
"lintel",
"live load",
"load bearing wall",
"loggia",
"lumens",
"lump sum bid",
"lump sum contract",
"mansard roof",
"masonry",
"meeting attendance form",
"meeting notes",
"milestone",
"millwork",
"monolithic",
"monopost",
"mylar",
"NEC",
"national electrical code",
"nonbearing wall",
"OC",
"on center",
"open bid",
"open estimate",
"orientation",
"outrigger",
"owner",
"onwner-architect agreement",
"owner-builder",
"owner-construction agreement",
"owner-construction management agreement",
"parapet",
"partition",
"performance bond",
"performance specifications",
"pergola",
"PERT",
"PERT Schedule",
"pier",
"pitch",
"plan view",
"planner",
"plans",
"plumbing trim",
"plumibing rough",
"post-and-beram",
"precast",
"pre-construction",
"predecessor",
"preliminary drawings",
"preliminary lien notice",
"pre-qualification of prospective bidders"];

function getSentence() { 
    return data[Math.floor(Math.random() * data.length)];
}

function getParagraph() {
    let result = [];
    const length = Math.floor(Math.random()*3+4);
    for (let i = 0; i< length; i++) {
        result.push(getSentence());
    }
    return result;
}
function getStory() {
    let result = [];
    const length = Math.floor(Math.random()*3+4);
    for (let i = 0; i< length; i++) {
        result.push(getParagraph());
        result.push('\n\n');
    }
    return result;
}

export function bimsum(type:bimtype) {
    
    const random = getSentence().split(' ');

    return {
        ['term']: terms[Math.floor(Math.random() * terms.length)],
        ['word']: random[Math.floor(Math.random() * random.length)],
        ['sentence']: getSentence(),
        ['paragraph']: getParagraph(),
        ['story']: getStory()
    }[type].toString();
}